### ISSUE TITLE
Allow configuring dependency repository lookups

### ISSUE THREAD

**Issue by tristanpemble** [datawire/forge#34]
When searching for a dependency, Forge tries looking up repositories using the current repo's origin. Sometimes, the repository might not be under the same organization, or even have the same name. It would be helpful to somehow be able to control what Forge searches for when looking up a particular dependency.

**Comment by tristanpemble** [comment]
Similar to #33, but for dependencies -- maybe something like:

```yaml
---
name: todo
requires:
  - search
  - git:
      service: tasks
      repo: https://github.com/datawire/todo
```

and could potentially be adapted to deal with Helm charts, or other types of dependencies:

```yaml
---
name: backend-service
requires:
  - helm:
      chart: mysql
      args: # ...
```
