### ISSUE TITLE
Templating with Jinja2/YAML

### ISSUE THREAD

**Issue by tristanpemble** [datawire/forge#38]
I'm gonna start off by saying that I'm not sure if there's a problem or a solution here. I guess I just wanted to have a discussion about the semantics of templating with Forge. Right now, templates are considered Jinja2 first, and then YAML. When I asked about this on Gitter, @rhs mentioned he wasn't sure if this was the right choice, it just was how he had implemented it at first. I _think_ it might work out to be the best implementation.

- What are the advantages of each approach? (YAML file with Jinja2 values, or a Jinja2 template rendering a YAML file)
- What existing examples of templated YAML are there?
  - Ansible (YAML file with Jinja2 values)
  - ???

I originally typed out a long example situation I ran into but it ended up not being relevant, so I boiled this issue down into some discussion points that might be good to have.

**Comment by tristanpemble** [comment]
Ugh, cmd+enter'd. Hate these new MBP keyboards. Will reopen when done typing the description

**Comment by tristanpemble** [comment]
Below are just notes of a situation I ran into..

Say I have a flag in my `service.yaml`, like `useSsl`. I want to toggle it with an environment variable. My first guess is to do something like:

```yaml
# service.yaml
useSsl: {{ env.SSL or false }}
```

```yaml
# k8s/ingress.yaml
# ...
metadata:
  annotations:
    kubernetes.io/tls-acme: {{ service.useSsl }}
    kubernetes.io/ingress.allow-http: {{ not service.useSsl }}
    ingress.kubernetes.io/force-ssl-redirect: {{ service.useSsl }}
# ...
```

```yaml
# rendered at work/k8s/ingress.yaml
# ...
metadata:
  annotations:
    kubernetes.io/tls-acme: True
    kubernetes.io/ingress.allow-http: False
    ingress.kubernetes.io/force-ssl-redirect: True
# ...
```

The problem here is that Kubernetes actually wants strings `"true"` and `"false"` so this manifest doesn't work.

So then I try `{{ 'true' if service.useSsl 'false' }}`, but that renders as `true`, still, even though it's a string in Jinja2. Which totally makes sense, once you run into it. This is a Jinja2 template, rendering text, that is later interpreted as YAML. You have to keep that in mind, but the mismatches can be a little weird.

So what I end up doing is `"{{'true' if service.useSsl 'false'}}"`, which finally renders `"true"`; it looks very strange.

It can give you a lot of flexibility, however, with conditional blocks, since you can sort of just form a YAML document however you want:

```yaml
# k8s/ingress.yaml
# ...
metadata:
    {% if service.useSsl %}
    kubernetes.io/tls-acme: 'true'
    kubernetes.io/ingress.allow-http: 'false'
    ingress.kubernetes.io/force-ssl-redirect: 'true'
    {% endif %}
```

**Comment by plombardi89** [comment]
Ansible 1.x had the same issue and I've been bitten and frustrated by it countless times in the past. Not sure about 2.x but I assume given it still uses Jinja2 and YAML that it has this issue as well. YAML is partially at fault here for allowing unquoted strings which are ambiguous in many cases. It's very frustrating. 

You can do this:

```yaml
# k8s/ingress.yaml
# ...
metadata:
  annotations:
    kubernetes.io/tls-acme: "{{ service.useSsl | lower }}"
    kubernetes.io/ingress.allow-http: "{{ not service.useSsl | lower }}"
    ingress.kubernetes.io/force-ssl-redirect: "{{ service.useSsl | lower }}"
# ...
```
