### ISSUE TITLE
Support build target in container build configuration

### ISSUE THREAD

**Issue by tristanpemble** [datawire/forge#45]
Reading #42 reminded me of a pattern I was thinking about implementing with my Dockerfiles with regard to [multi-stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/). These two might be slightly related, if the build target could be placed into the image tag. 

I was thinking about adding a build stage that includes the project debug/development dependencies preinstalled. Something like:

```Dockerfile
FROM php:7.1 AS debug

# ... make the debug build

FROM php:7.1 AS release

COPY --from=debug /app /app
# ... prune out debug stuff
```

If we could configure the build target, then I could do something like:

```yaml
containers:
  - dockerfile: ./Dockerfile
    target: {{ 'debug' if env.DEBUG else 'release' }}
```

and then with my proposed solution in #42, you could do this to avoid collisions on images:

```yaml
containers:
  - dockerfile: ./Dockerfile
    tag: {{version}}{%if env.DEBUG %}-debug{% endif %}
    target: {{ 'debug' if env.DEBUG else 'release' }}
```
