### ISSUE TITLE
Support configuration of container name

### ISSUE THREAD

**Issue by tristanpemble** [datawire/forge#46]
This is not that important, kind of cosmetic. I like to put all my "sub" container images in `./containers` folder, e.g. `./containers/proxy`. For a project named `my-api`, this creates an image named `my-api-containers-proxy`. I'd like to just name it `my-api-proxy`.

```yaml
containers:
  - name: my-api-proxy
    dockerfile: containers/proxy/Dockerfile
```
