### ISSUE TITLE
Ability to easily "forge pull"

### ISSUE THREAD

**Issue by tristanpemble** [datawire/forge#47]
Not sure this is the best solution, but if you are depending on forge to pull repositories for other services, it would be nice to have an easy way to pull the latest versions of all the requirements.

```yaml
name: root-level
requires:
  - api
  - backend
  - worker
```

`forge pull` would pull the latest versions of `api`, `backend` and `worker` from Git, as well as any of their dependencies

There might be a reason to have `forge pull [service]`, to control which service gets updated, but maybe not initially
