### ISSUE TITLE
Automatically merge "default" profile into the active profile

### ISSUE THREAD

**Issue by tristanpemble** [datawire/forge#82]
Discussed in Gitter:
```
name: my-service
profiles:
  stable:
    memory: { min: 0.5G }
    cpu: { max: 2 }
  default:
    ssl: true
    memory: { min: 0.1G, max: 1G }
    cpu: { min: 0.1, max: 1 }
```

running `forge --profile stable build metadata` would result in:

```yaml
# ...
build:
  profile:
    ssl: true
    memory:
      min: 0.5G
      max: 1G
    cpu:
      min: 0.1
      max: 2
# ...
